//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wipreport.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class siixsem_wip_control_dbEntities : DbContext
    {
        public siixsem_wip_control_dbEntities()
            : base("name=siixsem_wip_control_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WIP_RPT> WIP_RPT { get; set; }
        public virtual DbSet<siixsem_aging_rpt> siixsem_aging_rpt { get; set; }
        public virtual DbSet<WIP_RPT_FIN> WIP_RPT_FIN { get; set; }
        public virtual DbSet<WIP_RPT_OUT> WIP_RPT_OUT { get; set; }
    
        public virtual ObjectResult<getSMTIN_Result> getSMTIN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSMTIN_Result>("getSMTIN");
        }
    
        public virtual ObjectResult<AGING_REPORT_Result> AGING_REPORT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AGING_REPORT_Result>("AGING_REPORT");
        }
    
        public virtual ObjectResult<getSMTFIN_V_Result> getSMTFIN_V()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSMTFIN_V_Result>("getSMTFIN_V");
        }
    
        public virtual ObjectResult<getSMTOUT_Result> getSMTOUT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSMTOUT_Result>("getSMTOUT");
        }
    }
}
