//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wipreport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_aging_rpt
    {
        public int se_id { get; set; }
        public string LOCATOR { get; set; }
        public string MAGAZINE { get; set; }
        public string SCANED_SERIAL { get; set; }
        public string MODEL { get; set; }
        public string ROUTE { get; set; }
        public string DJGROUP { get; set; }
        public int QTY { get; set; }
        public string SEMIFINISH { get; set; }
        public string REVIEW { get; set; }
        public string TYPE { get; set; }
        public string QR { get; set; }
        public string USER_READ { get; set; }
        public string QUARANTINE { get; set; }
        public string VALIDATE_BY_QA { get; set; }
        public string USER_VALIDATE { get; set; }
        public string DATE_VALIDATED { get; set; }
        public string STATUS { get; set; }
        public string DATE_IN { get; set; }
        public string DATE_OUT { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int DAYS { get; set; }
        public string AGING { get; set; }
    }
}
